# Uncomment the next line to define a global platform for your project
# platform :ios, '12.3.1'

target 'Music-Appreciation-Mobile-App-iOs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  	# Pods for Music-Appreciation-Mobile-App-iOs
	pod 'Alamofire', '~> 4.0'

  target 'Music-Appreciation-Mobile-App-iOsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Music-Appreciation-Mobile-App-iOsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
